# Generated by Django 5.2.7 on 2025-10-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(max_length=30)),
                ("node_ip", models.GenericIPAddressField(unique=True)),
                ("node_password", models.CharField(max_length=255)),
                ("connected_node", models.GenericIPAddressField(default="127.0.0.1")),
                ("created_in", models.DateTimeField(auto_now_add=True)),
                ("updated_in", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
